apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mysql-secret-enc.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - ingress.yaml
  - redirect-ingress.yaml
