apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-redirect-404
  namespace: ingress-nginx
data:
  main.lua: |
    local ngx = ngx
    local _M = {}

    function _M.redirect_404()
      if ngx.status == 404 then
        ngx.redirect("https://www.google.com", 302)
      end
    end

    function _M.log()
      _M.redirect_404()
    end

    return _M
